### ISSUE TITLE
Trigger on User Object

### ISSUE THREAD

**Issue by cgjelsvik** [appero-com/MyTriggers#2]
How would you go about creating a User Trigger with this framework? Is it not possible due to limitations in the Custom Metadata field type Metadata Relationship?

**Comment by Szandor72** [comment]
I'd create an additional String field to accommodate until setup objects are better supported. 

In the framework code, I'd then check first if this string Field is filled and proceed from there. If not, I go by the required sObject Relation.

**Comment by Szandor72** [comment]
Workaround explained.
